name: Vulnerabilities Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skip-codeql-analyze:
        description: 'Skip CodeQL-Analyze'
        required: false
        default: false
        type: boolean
      skip-trivy-scan:
        description: 'Skip Trivy-Scan'
        required: false
        default: false
        type: boolean
      skip-zap-scan:
        description: 'Skip Zap-Scan'
        required: false
        default: false
        type: boolean

jobs:
  CodeQL-Analyze:
    if: ${{ github.event_name != 'workflow_dispatch' || !inputs.skip-codeql-analyze }}
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  Trivy-Scan:
    if: ${{ github.event_name != 'workflow_dispatch' || !inputs.skip-trivy-scan }}
    name: Trivy Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


  Zap-Scan:
    if: ${{ github.event_name != 'workflow_dispatch' || !inputs.skip-zap-scan }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
